name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: ai_game_builder_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Generate Prisma client
        working-directory: backend
        run: npx prisma generate
        env:
          DATABASE_URL: postgresql://postgres:test@localhost:5432/ai_game_builder_test

      - name: Run backend tests
        working-directory: backend
        run: npm test
        env:
          NODE_ENV: test
          DATABASE_URL: postgresql://postgres:test@localhost:5432/ai_game_builder_test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-secret

      - name: Build backend
        working-directory: backend
        run: npm run build

      - name: Verify no lockfile drift
        run: git diff --exit-code --name-only || (echo "Lockfile changed during backend job" && exit 1)

  mobile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            mobile/package-lock.json

      - name: Install mobile dependencies
        working-directory: mobile
        run: npm ci

      - name: Run mobile tests
        working-directory: mobile
        run: npm test -- --watchAll=false

      - name: Build mobile web
        working-directory: mobile
        run: npx expo export:web

      - name: Verify no lockfile drift
        run: git diff --exit-code --name-only || (echo "Lockfile changed during mobile job" && exit 1)

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json
            mobile/package-lock.json

      - name: Install root dependencies
        if: hashFiles('package.json') != ''
        run: npm ci

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install mobile dependencies
        working-directory: mobile
        run: npm ci

      - name: Lint backend
        working-directory: backend
        run: npm run lint

      - name: Lint mobile
        working-directory: mobile
        run: npm run lint

      - name: Verify no lockfile drift
        run: git diff --exit-code --name-only || (echo "Lockfile changed during lint job" && exit 1)

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    needs: [ backend-test, mobile-test, lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to staging
        run: echo "Deploy to staging environment"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: [ backend-test, mobile-test, lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        run: echo "Deploy to production environment"